language: common-lisp
sudo: false

addons:
  apt:
    packages:
    - zip

env:
  global:
  - GAMEKIT_SYSTEM_NAME: mds
  - GAMEKIT_APPLICATION_PACKAGE: mds
  - GAMEKIT_APPLICATION_MAIN_CLASS: example
  - PATH: ~/bin/:$PATH
  - GAMEKIT_TARGET_PACKAGE: $GAMEKIT_SYSTEM_NAME-x86-64-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip
  - GAMEKIT_BUILD_DIR: /tmp/$(GAMEKIT_SYSTEM_NAME)
  - secure: "pg5Pa9jOO/IuNHQ/NVJAV5Js1lpteX+wG7unUwZ0xU4BGXBV65iry3JC35/AyOvzHFZDY1IB3jYZ0oYQKmuixa1S9r/ZPKWCmUwo4W9XDoUvyrsTonQBXpZb4l0plI6fWdeLsjhbBra/y9Kb5Sc/oggKXwYzM7ibaLkUy5gDCe5PvJUOCWxtczcG4mV2IedST5KI/uMe0VS/VtDfW5GUdCSKCWuCdHA6u/f/CIfOi4jEHhxmcB/sNUscGcvu5XEkgfZM15O0ntfQ9f0tGiLTT0R+X81aViNubd6QZ/ChHmdJ0TEcxYCoDXfUY8BhCVCXQlD1lbCp3/WpRsDTQ1yGGDoSTv73Sow7X3DytZpkm4zjkuKyswFCg5CaoLBn46cMGv6yKq6Pai8LoX0hIZDUMqLR+C9m5BnGziTEo8+bAU/9PIF3cKmC/JD4Tz9huSskrdjnkWhdOa3Op0am9e0nDSiRZon+JsGsCj0xnXeq35ZHhe5UrFr7fQ606YXtx9J2n6Sv4761PLr60/OTMv/EzdtHiVq7DHgpAINwmLSdh/rJtWOuTj9CEJk793aJ5yFveGZL+3Fw+ohrDdsdzldSb8EycUtj3uYtwGK2oONaEwwLWY2nBMZ2TQ1CjIFj4qjmEPIHXepJmt1HyLKXDiIJcVXo4wu5sVbDuFfDy9gOq3w="

branches:
  only:
    - "/^v\\d+(\\.\\d+)+$/"

os:
  - linux
  - osx

install:
  - curl -L http://bodge.borodust.org/files/install.sh | sh

cache:
  directories:
  - "$HOME/opt/sbcl/"
  - "$HOME/.config/common-lisp/"

script:
  - >
    sbcl --script $HOME/bodge/scripts/build-gamekit-system.lisp
    $GAMEKIT_SYSTEM_NAME $GAMEKIT_APPLICATION_PACKAGE $GAMEKIT_APPLICATION_MAIN_CLASS
    $TRAVIS_BUILD_DIR
    $GAMEKIT_BUILD_DIR
before_deploy:
  - mv "$GAMEKIT_BUILD_DIR/$GAMEKIT_SYSTEM_NAME.zip" $GAMEKIT_TARGET_PACKAGE

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: $GAMEKIT_TARGET_PACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true